epi/epi/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^epivis/',include('epivis.urls')),
    url(r'^admin/', admin.site.urls),
]

epi/epivis/urls.py
from django.conf.urls import url
from . import views

app_name = 'epivis'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login', views.login, name='login'),
    url(r'^menu', views.menu, name='menu'),
    url(r'^refresh_basemount', views.refresh_basemount, name='refresh_basemount'),
    url(r'^show_files',views.show_files_page,name='show_files'),
    url(r'^get_files_info',views.get_files_info,name='get_files_info'),
]

epi/epivis/models.py
from django.db import models

class User(models.Model):
    #userid = models.AutoField(primary_key=True)
    username = models.CharField(max_length=30,unique=True)
    password = models.CharField(max_length=30)
    basemount_point = models.CharField(max_length=5000)
    #cache_path = models.CharField(max_length=5000)
    username_linux = models.CharField(max_length=30,unique=True,default='')
    password_linux = models.CharField(max_length=30,unique=True,default='')

class Project(models.Model):
    #projectid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200,unique=True)
    userid = models.ForeignKey(User,on_delete=models.CASCADE)

class Sample(models.Model):
    #sampleid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200,unique=True)
    projectid = models.ForeignKey(Project,on_delete=models.CASCADE)

class File(models.Model):
    name = models.CharField(max_length=200,unique=True)
    mate = models.IntegerField(default=-1)
    sampleid = models.ForeignKey(Sample,on_delete = models.CASCADE)
    feature = models.CharField(max_length=200)
    owner = models.CharField(max_length=200)
    viewer = models.CharField(max_length=200)
    path = models.CharField(max_length=200)
    createby = models.CharField(max_length=200)
    ancester = models.CharField(max_length=200,null=True)
    #sample          ForeignKey to sample

class Jobs(models.Model):
    cmd = models.CharField(max_length=300)
    priority = models.IntegerField()
    status = models.IntegerField()
    fullcmd = models.CharField(max_length=500)
    input = models.CharField(max_length=200,null=True)
    output = models.CharField(max_length=200,null=True)
    out = models.TextField()
    err = models.TextField()

class software(models.Model):
    name = models.CharField(max_length=50)
    comment = models.TextField()
    document_json = models.CharField(max_length=200)
    input = models.IntegerField()
    output = models.IntegerField()
    

# Create your models here.

epi/epivis/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .Test.module import *
from .util.ParseMetaInfo import *
from .util.GetNode import GetNode
from .models import *
from .util.Basemount import FS

# Create your views here.

def checklogin(request):
    if 'login' in request.session:
        if request.session['login']==1:
            return True
    return False

def refresh_basemount(request):
    if not checklogin(request):
        return index(request)
    filesystem = FS()
#account password path
    username = request.session['username']
    info = User.objects.filter(username = username)[0]
    account = info.username_linux
    password = info.password_linux
    path = info.basemount_point
    #print('Before return')
    #filesystem.refresh(account,password,path)
    #filesystem.GetProjects(path)
    try:
        filesystem.refresh(account,password,path)
        request.session['refresh_status']=True
    except Exception:
        request.session['refresh_status']=False
    finally:
        return redirect('/epivis/menu')
    

def index(request):
    #cal1()
    #print(cal1())
    #cm=cluster_manager()
    getmetainfo()
    #jq=job_queue()
    #if cm==None: redirect('/epivis/settings')
    name=''
    returnstring=''
    if 'login' in request.session:
        if not checklogin(request):
            returnstring = 'Wrong username or wrong password!'
            request.session.pop('login')
        else:
            menu(request)
    return render(request,'epivis/index.html',{'returnstring':returnstring})

def login(request):
    username = request.POST['username']
    password = request.POST['password']
    account=User.objects.filter(username = username, password=password)
    if len(account)!=1:
        request.session['login']=3
        return redirect('/epivis')
    else:
        request.session['login']=1
        request.session['username']=username
        request.session['id']=account[0].id
        try:
            FS().check_available()
        except Exception as e:
            print(e)
            if username!='root':
                print('error')
                return redirect('/epivis')
            else:
                return render(request,'epivis/set_meta.html',{'nodes':GetNode(),'cache_path':cache_path})#redirect(setting_meta)
        
        return redirect('/epivis/menu')

def get_meta(request):
    print('Get_meta')
    cache_path = request.POST['cache_path']
    nodes = request.POST['nodes']
    SetMeta(cache_path,nodes)
    return redirect(login)


    #User.objects.filter()
    #query = #get user information
    #if #No user has this username and password:
    #    request.session['login']=3
    #    return index(request)
    #else:
    #    request.session['login']=1
    #    request.session['username']=username
    #    return index(request)


def menu(request):
    if not checklogin(request):
        return index(request)
    username=request.session['username']
    return render(request,'epivis/menu.html',{'username':username})

def download_files(request):
    pass 

def file_detail(request):
    #Here we should pass the fileid using url
    fileid=0
    f = File.objects.get(id=fileid)
    sample = f.sampleid
    project = sample.projectid
    return render(request,'epivis/file_detail.html',{'project':project.name \
            ,'sample':sample.name,'filename':f.name,'mate':f.mate,'feature':f.feature})
    #return Project,Sample,filename,mate,feature


def show_files_page(request):
    if not checklogin(request):
        return index(request)
    username = request.session['username']
    u = User.objects.get(username=username)
    projects = FS().GetProjects(u.basemount_point)
    print(projects)
    return render(request,'epivis/show_files.html',{'username':username,'projects':projects})


#CHANGE JSON FILE FORMAT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#changed

def get_files_info(request):
#Get file information from sql and form json for javascript
    if not checklogin(request):
        return index(request)
    username = request.session['username']
    info = User.objects.filter(username = username)[0]
    #account = info.username_linux
    #password = info.password_linux
    path = info.basemount_point
    filesystem = FS()
    filesinfo = filesystem.GetProjects(path)#json
    #{Projects name:{Samples name:{filename:path}}}
    #Now it should be changed into:
    #{"Projects":[{"name":"projectname","Samples":["name":"samplename","Files":[{"name":"filename","path":"filepath"}]]}]}
    return filesinfo

epi/epivis/templates/epivis/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Epivis MS</title>
</head>
<body>
	<form method=post action="{% url 'epivis:login' %}">
	{% csrf_token %}
		<p>{{ returnstring }}</p>
		<label for="Username">Username:</label>
		<input name="username" id="Username" type="text"/>
		<label for="password">Password:</label>
		<input name="password" id="Password" type="password"/>
		<input type="submit" value="Log in"/>
	</form>
</body>
</html>

epi/epivis/templates/epivis/menu.html
<!DOCTYPE html>
<html>
<head>
	<title>Epivis Menu</title>
</head>
<body>
	<p>{{ username }}</p>
	<a href="{% url 'epivis:refresh_basemount' %}">Reload Basemount</a>
	<a href="{% url 'epivis:show_files' %}">Show Files</a>
	<a href="{% url 'epivis:download_files' %}">Downloaded Files</a>
	<a href="{% url 'epivis:analysis_result' %}">Analysis Result</a>
</body>
</html>

epi/epivis/templates/epivis/set_meta.html
<html>
<form action="{% url 'epivis:set_meta' %}" method="post">
	{% csrf_token %}
	<label for="cache_path">Cache Path</label>
	<input type="text" name="cache_path" id="cache_path" value="{{ cache_path }}">
	{% for node in nodes %}
		<label for="{{ node }}">{{ node }}</label>
		<input type="checkbox" name="{{ node }}" id="{{ node }}" checked>
	{% endfor %}
	<input type="submit" value="Submit">
</form>
</html>

epi/epivis/templates/epivis/show_files.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Show Files</title>
	<link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>	
	{% for project in projects.Projects %}
		<input type="checkbox" name="project" id="{{ project.name }}_project_checkbox" value="{{ project.name }}">
		<button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#{{ project.name }}_sample">{{ project.name }}</button>
		<div id="{{ project.name }}_sample" class="collapse">
		{% for sample in project.Samples %}
			<input type="checkbox" name="sample" id="sample_checkbox" value="{{ sample.name }}">
			<button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#{{ sample.name }}_file">{{ sample.name }}</button>
			<div id="{{ sample.name }}_file" class="collapse">
			{% for file in sample.Files %}
				<input type="checkbox" name="file" id="file_checkbox" value={{ file.id }}>
				<a href="">{{ file.name }}</a>
			{% endfor %}
			</div>
		{% endfor %}
		</div>
	{% endfor %}
<!--I think we could get elements by name=="file" and checked feature. Then form a file.id list and turn it back to view. Then we could check whether the file has been downloaded. -->
	<script>
		$(document).ready(function(){
			$("sample_checkbox").click(function(){
				if (this.checked) {
					$("input[name='file']")
				}
			});
		})
	</script>
</body>
</html>